Add reminder
siiibo/shujinosuke pull request #10
Opened 2020-10-14 02:19 UTC by masam0

週次開始から3分後に、チャンネル内の未参加者へ週次のリマインドをする機能を追加しました。
主な変更点は以下の通りです。

- 開始後3分で"check_participants"イベントをトリガー。

- チャンネル参加者と、週次参加者を比較し、週次に参加していない人へEphemeralメッセージでリマインド。

レビューをお願いします。

2020-10-14 04:29 UTC, masam0 commented
![](https://github.trello.services/images/mini-trello-icon.png) [全体週次のファシリテーションBot「Shujinosuke」を改善](https://trello.com/c/d6RTjCE6/612-%E5%85%A8%E4%BD%93%E9%80%B1%E6%AC%A1%E3%81%AE%E3%83%95%E3%82%A1%E3%82%B7%E3%83%AA%E3%83%86%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3bot%E3%80%8Cshujinosuke%E3%80%8D%E3%82%92%E6%94%B9%E5%96%84)

2020-10-14 05:19 UTC, ymtszw commented on src/features/shujinosuke.js
> +    });
conversationのmembersは、例えば社外取締役の多喜（Oki）さんなど、オブザーバー参加の方もいて、huddleに参加すべき人のリストとしては若干不正確です。
また、その日欠席していることがわかっている人がinviteされるのも若干スマートでない。

* 多喜さんのような方に関しては除外対象としてハードコードしておいてもいいでしょう（Shujinosuke自身を除外しているのと同様）
* 欠席者がinviteされるのに関しては、今現在、または数時間以内にオンラインだったかどうかによる判定を加えてみてもいいかも

2020-10-19 01:17 UTC, masam0 commented on src/features/shujinosuke.js
> +        !observers.includes(member) //Removing observers and shujinosuke
オブザーバー参加者のID入り配列を作成し、それらのIDはここで除かれるようになっています。

2020-10-19 01:17 UTC, masam0 commented on src/features/shujinosuke.js
> +
本来であれば295行目のfilterで、ステータスが `:yasumi:`の人も同時に取り除くつもりでしたが、上手く動作しなかったため通知メッセージ生成と同じ関数の中で処理をしています。(問題の詳細な原因は分かりませんでしたが、filter中のasync functionの呼び出し方が問題だったと考えています。)

2020-10-19 01:22 UTC, masam0 commented on src/features/shujinosuke.js
> +    });
attendanceチャンネルとステータスの連携があれば「OO時間内にオンラインだった」という出欠席の判定基準は必要なさそうなので、attendanceチャンネルとの連携を行います。それにあたり、shujinosukeに `users.profile.write`のScopeを加えてチャンネルに再インストールしたいのですが、よろしいでしょうか？

2020-10-19 04:51 UTC, ymtszw commented on src/features/shujinosuke.js
> +    });
OKです！

2020-10-19 04:54 UTC, masam0 commented on src/features/shujinosuke.js
> +    });
了解しました。次回出勤時にこちらのScopeを追加し、カスタムステータスとattendanceチャンネル連携を実装していきます。

2020-10-21 02:42 UTC, masam0 commented on src/features/shujinosuke.js
> +      };
attendanceチャンネルのログを見たところ、このリスト中のemojiが頻繁に使われていました。
他に`離席中`などの使用も見られましたが、カスタムステータス への反映の必要性が低そうであったため、リストから省きました。今後`離席中`の人を週次に自動インバイトしないといった機能を実装するようであれば、カスタムステータスに`離席中`もしくは`DND`ステータスと対応させることで楽に実装できると思います。

2020-10-21 02:42 UTC, masam0 commented on src/features/shujinosuke.js
> +      const user_token = process.env.USERS_TOKEN;
@ymtszw 
custom state書き換えに `user` タイプのトークンが必要であるため、shujinosukeにスコープを追加し、.envファイルに情報を記述しました。デプロイ時にデプロイ先の .env ファイルの書き換えをしないとクラッシュしてしまうため注意が必要です。

2020-10-30 10:21 UTC, ymtszw commented
口頭でやりましたが、ステータスを前提とする処理はステータス変更の権限をbotに与えるワークフローの構築が難しそうなので、成立しなそうです。
presenceの仕様を調べてもらって、そこから情報を取ることにしましょう。
presenceはあまりきめ細かく設定できませんが、そこまで正確に取れなくてOKです。

2020-11-02 04:46 UTC, masam0 commented on src/features/shujinosuke.js
> +      const all_members_response = await bot.api.users.list({});
コミット "Change "今いる人は？" command using user presence" では、"今いる人は？"コマンドでオンライン中のメンバー名を正しく発言するのですが、コマンド内の関数の挙動が複数回繰り返されてしまう挙動が確認されています。（結果としてbotが複数回発言する。）

試しにメンバーIDを取得するapiを `users.list` から`conversations.members` にしたら直ったのですが、具体的な原因は不明です。 `users.list` を使用した状態でリピートが起きないような対処法を探します。

2020-11-02 05:13 UTC, ymtszw commented on src/features/shujinosuke.js
> +      const all_members_response = await bot.api.users.list({});
Slackのevent送信の仕様が原因かも。event送信に対してすぐ（具体的な閾値はわからない）レスポンスを返さなかった場合、Slackはeventを再送信することがあります（"exactly once"でない）。なんでかというとusers.list + 人数分getPresenceはまあまあ時間がかかるからと想像。

こういうのは非同期化するのが正しくて、hearsの処理自体は次のイベントを発火するにとどめて処理を完了します。具体的なAPI呼び出しや返信処理は次のイベントに対応する処理として実行しましょう。
するとSlackからはすぐ処理が完了したように見えるので重複送信はなくなると思います（少なくとも大抵は）。Shujinosuke側としては次のイベントで具体的な内容を実行すればいいので、多少時間がかかっても問題ない。

2020-11-02 05:15 UTC, ymtszw commented
review readyになったらpingしてください。
また、別機能実装するときはbranchを分けましょう。

2020-11-04 02:03 UTC, masam0 commented on src/features/shujinosuke.js
> +  `;
[trelloでの廣瀬さんからの指摘](https://trello.com/c/d6RTjCE6/612-%E5%85%A8%E4%BD%93%E9%80%B1%E6%AC%A1%E3%81%AE%E3%83%95%E3%82%A1%E3%82%B7%E3%83%AA%E3%83%86%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3bot%E3%80%8Cshujinosuke%E3%80%8D%E3%82%92%E6%94%B9%E5%96%84)を基に、表示するのはあくまでアクティブユーザーであることを明記しました。少し周りくどい文章ではありますが、これで表示される方の判定方法は皆さんに伝わるのではないかと思います。

2020-11-04 04:35 UTC, ymtszw commented on src/features/shujinosuke.js
> +  :warning: あくまで状態がアクティブなユーザーを表示しているので、勤務者とは限りません。
```suggestion
  :warning: あくまでSlackの状態がアクティブなユーザーを表示しているので、出社しているとは限りません。
```
こうかな。

2020-11-04 04:39 UTC, ymtszw commented on src/features/shujinosuke.js
> +      .filter((attendee_id) => attendee_id)
この`.filter()`の意図は？`member.id`がfalsy（null）の可能性がある？

2020-11-04 04:42 UTC, ymtszw commented on src/features/shujinosuke.js
> +  :warning: あくまで状態がアクティブなユーザーを表示しているので、勤務者とは限りません。
```suggestion
  :warning: あくまでSlackの状態がアクティブなユーザーを表示しているので、勤務しているとは限りません。
```
こうでもいい。

2020-11-04 04:43 UTC, ymtszw requested changes
だいたいいい感じなので、あとは最新のコメント分くらい。

2020-11-04 05:04 UTC, masam0 commented on src/features/shujinosuke.js
> +  :warning: あくまで状態がアクティブなユーザーを表示しているので、勤務者とは限りません。
より広い意味を持つ後者にします。

2020-11-04 05:11 UTC, masam0 commented on src/features/shujinosuke.js
> +      .filter((attendee_id) => attendee_id)
attendees_txtの取り方に変更加えた際に消し忘れたものだと思います。
念のためこの部分を消して動作確認したら最終版としてpushします。

2020-11-06 08:32 UTC, masam0 commented on src/features/shujinosuke.js
> +      .filter((attendee_id) => attendee_id)
この部分について、314行目からのmap内の関数でユーザのpresenceが `active` である場合のみそのユーザのIDを返し、それ以外の場合は戻り値を指定していないため、async関数の仕様上undefinedを返すのに対応するための処理でした。このフィルターを通して shujinosukeが "@undefined" と発言するのを防止しています。

2020-11-06 10:36 UTC, ymtszw commented on src/features/shujinosuke.js
> +        }
ここを
```suggestion
        if (presence_response.presence === "active") {
          return member.id;
        } else {
          return null
        }
```
明示的にこうしましょう。するとその後のfilterがnullを弾いてんだなとわかる。

2020-11-06 10:41 UTC, ymtszw commented on src/features/shujinosuke.js
> +      .filter((attendee_id) => attendee_id)
さらに
```suggestion
      .filter((attendee_id) => attendee_id != null)
```
こうするとはっきりする

2020-11-06 10:53 UTC, ymtszw approved these changes
# okay

試してみましょう。

2020-11-06 10:53 UTC, merged