ヘルプコマンド表示内容の関数化
siiibo/shujinosuke pull request #6
Opened 2020-09-24 03:32 UTC by masam0

先日送ったPR(Fix Help)でご指摘のあったコードの冗長さを、関数を用いて簡潔に表しました。動作イメージはTrelloのカードに添付しておきましたので、そちらでご確認をお願いします。

2020-09-24 04:51 UTC, ymtszw commented on src/features/shujinosuke.js
> +  controller.hears(
`controller`にevent handler関数を登録する処理は、それぞれ間に空行はさみましょう。区切りをわかりやすくするため。
prettierなどのformatterで強制されないスタイルについては、基本的に周囲のコードを見てパターンを揃えるのがコツです。

2020-09-24 05:07 UTC, ymtszw commented on src/features/shujinosuke.js
> +    }
順序にこだわらないのであれば[`Object.entries()`](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Object/entries)が使えます。
また、これはarrayを返すので`map`できるようになり、それを`join`できます。

```js
const commands =
  Object.entries(help_commands_off)
    .map((key, val) => key + "\n" + val)
    .join("\n\n")
return ':books:会議開始前にShujinosukeで使えるコマンドは以下の通りです！\n:bulb:コマンドの前には必ず "@Shujinosuke" をつけましょう！\n\n' + commands
```
想定通り動かない部分は調整してください。

2020-09-24 05:08 UTC, ymtszw commented on src/features/shujinosuke.js
> +    message_txt = help_commnads_off_array.join(",").split(",").join(" ");
この処理の意図がよくわからないのですが、`" "`でつなげてるのってどのへんに影響してますか？
また、単に`help_commnads_off_array.join(" ")`で良さそうに見える。

2020-09-24 05:15 UTC, ymtszw commented
これcloseされてますが、誤操作？
基本的にPRは大きな方針転換をするとかでなければmergeに至るまでopenのままでOKです。

2020-09-24 05:22 UTC, masam0 commented
@ymtszw githubにおけるルールがまだあまり把握できていないため、初めのレビューと共にcloseしてしまいました。すみません。このPRも一応Reopenしときます。

2020-09-24 05:24 UTC, ymtszw commented
#dev-portalおよびsiiibo-appリポジトリでのやり取りなどを参考にしてください。
https://github.com/siiibo/siiibo-app/pulls

2020-09-29 01:48 UTC, masam0 reviewed
@ymtszw さんにレビューしていただいた通り、`Object.entries()` を使用してコードを書き直しました。`map()` については、引数を二つ指定してしまうと配列のkey (0, 1, 2...)と value ([会議の開始, `開始`], [会議の強制終了, `終了` `リセット` `reset`])の両方が出力されてしまうため、配列のvalueの要素を指定して組み合わせるという方針に切り替えました。

2020-09-29 01:49 UTC, masam0 commented on src/features/shujinosuke.js
> +    message_txt = help_commnads_off_array.join(",").split(",").join(" ");
v

2020-09-29 01:51 UTC, masam0 commented on src/features/shujinosuke.js
> +    message_txt = help_commnads_off_array.join(",").split(",").join(" ");
そうですね...　この方針でコードを書くにしても `help_commnads_off_array.join(" ")` で十分でした。
変更したコードにはこの操作は含まれていないので問題ありません。

2020-09-29 01:54 UTC, masam0 commented on src/features/shujinosuke.js
> +    );
@ymtszw さんにレビューしていただいた通り、`Object.entries()` を使用してコードを書き直しました。`map()` については、引数を二つ指定してしまうと配列のkey (0, 1, 2...)と value ([会議の開始, `開始`], [会議の強制終了, `終了` `リセット` `reset`])の両方が出力されてしまうため、配列のvalueの要素を指定して組み合わせるという方針に切り替えました。

2020-10-01 06:07 UTC, ymtszw commented on src/features/shujinosuke.js
> +      .map((x) => "\n" + x[0] + "\n" + x[1])
> 引数を二つ指定してしまうと配列のkey (0, 1, 2...)と value ([会議の開始, 開始], [会議の強制終了, 終了 リセット reset])の両方が出力されてしまうため

なるほど、
```js
      .map(([key, val]) => key + "\n" + val)
      .join("\n\n");
```
こうでしたね。
「配列として受け取る」ことができて、destructuringといって該当する位置の要素を直接変数に束縛できます。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

あと、改行文字やスペースでjoinするときは全体的な構造に即した位置に適切に詰めるとベター（ここでは、空行をはさんでjoinしたい、ということなので`"\n\n"`でjoinする）。

2020-10-01 06:08 UTC, ymtszw commented on src/features/shujinosuke.js
> +function gen_message() {
関数名は`help_messege()`や`gen_help_message()`かな。何のメッセージ化を明示しよう。

2020-10-01 06:15 UTC, ymtszw requested changes
だいぶいい感じになりました。あと2点

2020-10-02 08:32 UTC, masam0 commented on src/features/shujinosuke.js
> +      .join("\n\n");
@ymtszw さんのレビューに従って、gen_messageをgen_help_messageに、mapの引数を Destructuring assignmentを使用して表しました。レビューをお願いします。

2020-10-02 09:05 UTC, ymtszw approved these changes
# okay

👍 Mergeします！

2020-10-02 09:05 UTC, merged

2020-10-02 09:12 UTC, ymtszw commented
![](https://github.trello.services/images/mini-trello-icon.png) [全体週次のファシリテーションBot「Shujinosuke」を改善](https://trello.com/c/d6RTjCE6/612-%E5%85%A8%E4%BD%93%E9%80%B1%E6%AC%A1%E3%81%AE%E3%83%95%E3%82%A1%E3%82%B7%E3%83%AA%E3%83%86%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3bot%E3%80%8Cshujinosuke%E3%80%8D%E3%82%92%E6%94%B9%E5%96%84)